import json
import os
import re

# --- Configuration ---
full_data_json_path = "/home/ubuntu/site_bazar/full_item_data_translated.json" # This should have the status field
output_site_dir = "/home/ubuntu/site_bazar"
whatsapp_number = "+351915722650"
footer_text_additional = "Faro | Algarve | Portugal"

# --- Helper to sanitize for HTML filenames ---
def sanitize_filename(name):
    name = str(name)
    name = re.sub(r'[^a-zA-Z0-9_\-\.]', '_', name)
    name = re.sub(r'_+', '_', name)
    return name.lower()

# --- Load Data ---
try:
    with open(full_data_json_path, 'r', encoding='utf-8') as f:
        items = json.load(f)
except FileNotFoundError:
    print(f"Error: {full_data_json_path} not found. Cannot generate homepages.")
    exit()
except json.JSONDecodeError:
    print(f"Error: Could not decode JSON from {full_data_json_path}.")
    exit()

# --- Ensure style.css exists (it should have been created by the item page generator with new styles) ---
css_file_path = os.path.join(output_site_dir, "style.css")
if not os.path.exists(css_file_path):
    print(f"Warning: {css_file_path} not found. Homepage might not be styled correctly. It should be generated by generate_separate_item_pages_translated.py")

footer_whatsapp_link = f"https://wa.me/{whatsapp_number.replace('+', '')}"

# --- Generate Portuguese Homepage (index-pt.html) ---
index_pt_content = f"""
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bazar de Mudança - Itens à Venda</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1><a href="index-pt.html">Bazar de Mudança</a></h1>
        <div class="lang-switcher-home">
            <a href="index-en.html">🇬🇧 En</a>
        </div>
    </header>
    <div class="container">
        <h2>Itens Disponíveis</h2>
        <div class="item-grid">
"""
for item in items:
    item_id_sanitized = sanitize_filename(item.get("id", "unknown_id"))
    title_pt = item.get("title_pt", "Item sem título")
    price = item.get("price", "0.00")
    status = item.get("status", "available") # Get status, default to available
    thumbnail_img = item.get("images", ["assets/img/placeholder.png"])[0] if item.get("images") else "assets/img/placeholder.png"
    item_page_url_pt = f"item-{item_id_sanitized}-pt.html"

    reserved_badge_html = ""
    status_text_html = "<span class=\"status-text\">disponível agora</span>"
    if status == "reserved":
        reserved_badge_html = "<div class=\"reserved-badge\">Reservado</div>"
        status_text_html = "" # No 'disponível agora' if reserved

    index_pt_content += f"""
            <div class="item-card">
                <div class="image-container">
                    {reserved_badge_html}
                    <a href="{item_page_url_pt}"><img src="{thumbnail_img}" alt="{title_pt}"></a>
                </div>
                <h3><a href="{item_page_url_pt}">{title_pt}</a></h3>
                <div class="price-section">
                    <p class="price">€ {price}</p>
                    {status_text_html}
                </div>
            </div>
"""
index_pt_content += f"""
        </div>
    </div>
    <footer>
        <p>Todos os itens à venda. Contacte para mais informações.</p>
        <p><a href="{footer_whatsapp_link}" target="_blank" rel="noopener">WhatsApp: {whatsapp_number}</a> | {footer_text_additional}</p>
    </footer>
</body>
</html>
"""
with open(os.path.join(output_site_dir, "index-pt.html"), 'w', encoding='utf-8') as f:
    f.write(index_pt_content)
print("Generated index-pt.html with status indicators.")

# --- Generate English Homepage (index-en.html) ---
index_en_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moving Sale Bazaar - Items for Sale</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <h1><a href="index-en.html">Moving Sale Bazaar</a></h1>
        <div class="lang-switcher-home">
            <a href="index-pt.html">🇵🇹 Pt</a>
        </div>
    </header>
    <div class="container">
        <h2>Available Items</h2>
        <div class="item-grid">
"""
for item in items:
    item_id_sanitized = sanitize_filename(item.get("id", "unknown_id"))
    title_en = item.get("title_en", "Untitled Item")
    price = item.get("price", "0.00")
    status = item.get("status", "available") # Get status
    thumbnail_img = item.get("images", ["assets/img/placeholder.png"])[0] if item.get("images") else "assets/img/placeholder.png"
    item_page_url_en = f"item-{item_id_sanitized}-en.html"

    reserved_badge_html_en = ""
    status_text_html_en = "<span class=\"status-text\">available now</span>"
    if status == "reserved":
        reserved_badge_html_en = "<div class=\"reserved-badge\">Reserved</div>"
        status_text_html_en = ""

    index_en_content += f"""
            <div class="item-card">
                <div class="image-container">
                    {reserved_badge_html_en}
                    <a href="{item_page_url_en}"><img src="{thumbnail_img}" alt="{title_en}"></a>
                </div>
                <h3><a href="{item_page_url_en}">{title_en}</a></h3>
                <div class="price-section">
                    <p class="price">€ {price}</p>
                    {status_text_html_en}
                </div>
            </div>
"""
index_en_content += f"""
        </div>
    </div>
    <footer>
        <p>All items for sale. Contact for more information.</p>
        <p><a href="{footer_whatsapp_link}" target="_blank" rel="noopener">WhatsApp: {whatsapp_number}</a> | {footer_text_additional}</p>
    </footer>
</body>
</html>
"""
with open(os.path.join(output_site_dir, "index-en.html"), 'w', encoding='utf-8') as f:
    f.write(index_en_content)
print("Generated index-en.html with status indicators.")

print(f"Bilingual homepages with status indicators generated in {output_site_dir}")

